name: Symfony CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip

      - name: Build
        run: make build

      - name: Prepare artifacts
        run: mkdir -p vendor bin var

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            vendor/
            bin/
            var/

  quality:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Restore executable permissions
        run: chmod +x vendor/bin/*

      - name: Warm up Symfony cache
        run: php bin/console cache:warmup

      - name: Run PHP CS Fixer
        run: make cs-fixer

      - name: Run PHPStan
        run: make phpstan

      - name: Run Rector
        run: make rector

  tests:
    needs: quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip
          coverage: pcov

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Restore executable permissions
        run: chmod +x vendor/bin/*

      - name: PHPUnit with coverage
        run: make tests-with-coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/

  api-tests:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: zip

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.2'

      - name: Run Bruno API tests
        run: make api-tests
